name: Update gist with WakaTime stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 48675a7b5e3cca534e7817595d566003
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
